spring.application.name: ${app.name}

spring.main.banner-mode: off

logging.level.ROOT: WARN
logging.level.io.leangen: ERROR
logging.level.ext.springboot: INFO
logging.level.org.springframework: ${SPRING_LOG_LEVEL:WARN}
logging.level.liquibase: ERROR
logging.level.dev.soffa: ${PLATFORM_LOG_LEVEL:INFO}
logging.level.foundation: ${PLATFORM_LOG_LEVEL:INFO}
logging.level.app: ${LOG_LEVEL:INFO}
logging.level.service: ${LOG_LEVEL:INFO}


spring.profiles.group.production: ${environments.production.include:default}
spring.profiles.group.staging: ${environments.staging.include:default}
spring.profiles.group.qa: ${environments.qa.include:default}
spring.profiles.group.uat: ${environments.uat.include:default}
spring.profiles.group.dev: ${environments.dev.include:default}
spring.profiles.group.integration: ${environments.integration.include:default}
spring.profiles.group.local: ${environments.local.include:default}

# completely remove it
logging.level.org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration: OFF

spring.jackson.default-property-inclusion: non_empty
spring.jackson.property-naming-strategy: ${jackson.property-naming-strategy:LOWER_CAMEL_CASE}
spring.jackson.serialization.write-dates-as-timestamps: true

spring.output.ansi.enabled: always


server.compression.enabled: true
server.forward-headers-strategy: framework
server.port: ${PORT:8080}


management.endpoints.web.exposure.include: info,health,prometheus,metrics,refresh

management.endpoint.health.enabled: true
management.endpoint.health.show-components: when-authorized
management.endpoint.health.show-details: when-authorized

management.metrics.export.simple.enabled: true
management.health.diskspace.enabled: true
management.health.db.enabled: true
management.health.rabbit.enabled: true

spring.groovy.template.check-template-location: false

springdoc.api-docs.enabled: true
springdoc.show-actuator: false
springdoc.paths-to-exclude: graphiql, /graphiql, error, /error, /oauth/*, /user/auth, /actuator/*, /healthz
springdoc.show-login-endpoint: false
springdoc.swagger-ui.enabled: ${app.swagger-ui.enabled:true}
springdoc.swagger-ui.operations-sorter: alpha
springdoc.swagger-ui.tags-sorter: alpha


app.consul.enabled: false
spring.cloud.consul.enabled: false
spring.cloud.consul.config.enabled: false
spring.cloud.consul.discovery.enabled: false


spring.autoconfigure.exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
management.endpoint.health.group.liveness.include: livenessstate,cacheCheck
management.endpoint.health.probes.enabled: true

app.redoc.enabled: true

spring.jackson:
  default-property-inclusion: non_null

spring.cloud.vault.enabled: false
spring.cloud.vault.kv.enabled: false

spring.jpa.open-in-view: false
spring.jpa.show-sql: false
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.batch_size: 500
spring.jpa.hibernate.ddl-auto: none
spring.jpa.hibernate.naming.physical-strategy: dev.soffa.foundation.data.spring.CustomPhysicalNamingStrategy

spring.liquibase.enabled: false

app.openapi.enabled: true
app.openapi.access: permitAll
app.openapi.title: ${spring.application.name}

app.health.root.enabled: false

org.jobrunr.background-job-server.enabled: ${app.jobs.enabled:false}
org.jobrunr.dashboard.enabled: ${app.jobs.enabled:false}
org.jobrunr.database.skip_create: true
org.jobrunr.dashboard.port: 8000
junit.jupiter.execution.parallel.enabled: true

spring.sleuth.web.skipPattern: (^cleanup.*|.+favicon.*)

spring.zipkin.enabled: ${app.zikin.enabled:${ZIPKIN_ENABLED:true}}
spring.zipkin.base-url: ${app.ziking.url:${ZIPKIN_BASE_URL:localhost:9411}}

spring.sleuth.web.client.enabled: ${ZIPKIN_ENABLED:true}

spring.webflux.static-path-pattern: /assets/**

server.servlet.contextPath: ${app.context-path:${CONTEXT_PATH:}}


---
spring.config.activate.on-profile: test

management.health.vault.enabled: false
logging.level.dev.soffa: DEBUG
logging.level.foundation: DEBUG
management.endpoint.health.show-components: always
management.endpoint.health.show-details: always


---
spring.config.activate.on-profile: production,prd,prod
spring.config.import:
  - classpath:application-json-logs.yml
